Create Database Hospital
Go
Use Hospital
Go
Create Table Patient_Summary (
	encounterID Int Not Null,
	age TinyInt Not Null,
	edVisitCountPast3months TinyInt Not Null,
	admissionMonth TinyInt Not Null,
	admissionBetweenThuAndSat Bit Not Null,
	edTimeBeforeAdmission Float,
	firstTemperatureReadingInED Float,
	meanLOSPast24months Float,
	inpatientAdmitCountPast3months TinyInt Not Null,
	meanTemperaturePast12months Float,
	inpatientAdmitCountPast6months TinyInt Not Null,
	inpatientAdmitCountPast12months TinyInt Not Null,
	hospitalAdmitCountPast3months TinyInt Not Null,
	hospitalAdmitCountPast6months TinyInt Not Null,
	edVisitCountPast6months TinyInt Not Null,
	medianTemperaturePast12months Float,
	meanHeartRatePast12months Float,
	isFirstTemperatureInEDLess34OrGreater38 Bit,
	firstHeartRateReadingInED Float,
	hospitalAdmitCountPast12months TinyInt Not Null,
	edVisitCountPast12months Int Not Null,
	daysSinceLastInpatientEncounter SmallInt Not Null,
	meanAlbuminPast12months Float,
	meanCreatininePast12months Float,
	meanGlucosePast12months Float,
	meanSodiumPast12months Float,
	meanBilirubinPast12months Float,
	meanWBCCountPast12months Float,
	meanSerumBicarbonatePast12months Float,
	meanPotassiumPast12months Float,
	medianHeartRatePast12months Float,
	minHeartRatePast12months Float,
	maxHeartRatePast12months Float,
	lastHeartRatePast12months Float,
	minTemperaturePast12months Float,
	maxTemperaturePast12months Float,
	lastTemperaturePast12months Float,
	medianLOSPast24months Float,
	minLOSPast24months Float,
	maxLOSPast24months Float,
	modeLOSPast24months Float,
	isFirstHeartRateInEDLess60OrGreater110 Bit,
	medianAlbuminPast12months Float,
	minAlbuminPast12months Float,
	maxAlbuminPast12months Float,
	lastAlbuminPast12months Float,
	medianBilirubinPast12months Float,
	minBilirubinPast12months Float,
	maxBilirubinPast12months Float,
	lastBilirubinPast12months Float,
	medianCreatininePast12months Float,
	minCreatininePast12months Float,
	maxCreatininePast12months Float,
	lastCreatininePast12months Float,
	medianGlucosePast12months Float,
	minGlucosePast12months Float,
	maxGlucosePast12months Float,
	lastGlucosePast12months Float,
	medianPotassiumPast12months Float,
	minPotassiumPast12months Float,
	maxPotassiumPast12months Float,
	lastPotassiumPast12months Float,
	medianSodiumPast12months Float,
	minSodiumPast12months Float,
	maxSodiumPast12months Float,
	lastSodiumPast12months Float,
	medianSerumBicarbonatePast12months Float,
	minSerumBicarbonatePast12months Float,
	maxSerumBicarbonatePast12months Float,
	lastSerumBicarbonatePast12months Float,
	meanHematocritPast12months Float,
	medianHematocritPast12months Float,
	minHematocritPast12months Float,
	maxHematocritPast12months Float,
	lastHematocritPast12months Float,
	meanAlkalinePhosphatasePast12months Float,
	medianAlkalinePhosphatasePast12months Float,
	minAlkalinePhosphatasePast12months Float,
	maxAlkalinePhosphatasePast12months Float,
	lastAlkalinePhosphatasePast12months Float,
	meanHbA1cPast12months Float,
	medianHbA1cPast12months Float,
	minHbA1cPast12months Float,
	maxHbA1cPast12months Float,
	lastHbA1cPast12months Float,
	meanNeutrophilsPast12months Float,
	medianNeutrophilsPast12months Float,
	minNeutrophilsPast12months Float,
	maxNeutrophilsPast12months Float,
	lastNeutrophilsPast12months Float,
	meanASTPast12months Float,
	medianASTPast12months Float,
	minASTPast12months Float,
	maxASTPast12months Float,
	lastASTPast12months Float,
	meanALTPast12months Float,
	medianALTPast12months Float,
	minALTPast12months Float,
	maxALTPast12months Float,
	lastALTPast12months Float,
	meanLactatePast12months Float,
	medianLactatePast12months Float,
	minLactatePast12months Float,
	maxLactatePast12months Float,
	lastLactatePast12months Float,
	meanINRPast12months Float,
	medianINRPast12months Float,
	minINRPast12months Float,
	maxINRPast12months Float,
	lastINRPast12months Float,
	maxTroponinIHSPast12months Float,
	lastTroponinIHSPast12months Float,
	actualLOS Float Not Null,
	maritalStatus VarChar(20) Constraint maritalStatus_Domain Check (maritalStatus in ('divorced','domestic-partner','married','never-married','widowed')),
	primaryDiagnosisChronicCondition Float,
	chronicConditionCount TinyInt Not Null,
	isChronicConditionDementia Bit Not Null,
	isChronicConditionAcuteHypothyroidism Bit Not Null,
	isChronicConditionAcuteMyocardialInfarction Bit Not Null,
	isChronicConditionAlzheimersDisease Bit Not Null,
	isChronicConditionAnemia Bit Not Null,
	isChronicConditionAsthma Bit Not Null,
	isChronicConditionAFib Bit Not Null,
	isChronicConditionCataract Bit Not Null,
	isChronicConditionCOPD Bit Not Null,
	isChronicConditionDepression Bit Not Null,
	isChronicConditionDiabetes Bit Not Null,
	isChronicConditionHeartFailure Bit Not Null,
	isChronicConditionHyperlipidemia Bit Not Null,
	isChronicConditionHypertension Bit Not Null,
	isChronicConditionIschemicHeartDisease Bit Not Null,
	isChronicConditionOsteoporosis Bit Not Null,
	isChronicConditionBreastCancer Bit Not Null,
	isChronicConditionColorectalCancer Bit Not Null,
	isChronicConditionProstateCancer Bit Not Null,
	isChronicConditionLungCancer Bit Not Null,
	isChronicConditionEndometrialCancer Bit Not Null,
	sdAlbuminPast12months Float,
	sdSerumBicarbonatePast12months Float,
	sdSodiumPast12months Float,
	sdPotassiumPast12months Float,
	sdBilirubinPast12months Float,
	sdCreatininePast12months Float,
	sdGlucosePast12months Float,
	sdHematocritPast12months Float,
	sdNeutrophilsPast12months Float,
	sdAlkalinePhosphatasePast12months Float,
	sdASTPast12months Float,
	sdALTPast12months Float,
	sdLactatePast12months Float,
	sdINRPast12months Float,
	charlsonComorbidityIndex Float Not Null,
	bmi Float,
	adjustedLOS Float,
	meanSystolicBPPast12months Float,
	medianSystolicBPPast12months Float,
	minSystolicBPPast12months Float,
	maxSystolicBPPast12months Float,
	lastSystolicBPPast12months Float,
	sdSystolicBPPast12months Float,
	meanDiastolicBPPast12months Float,
	medianDiastolicBPPast12months Float,
	minDiastolicBPPast12months Float,
	maxDiastolicBPPast12months Float,
	lastDiastolicBPPast12months Float,
	sdDiastolicBPPast12months Float,
	meanRespirationPast12months Float,
	medianRespirationPast12months Float,
	minRespirationPast12months Float,
	maxRespirationPast12months Float,
	lastRespirationPast12months Float,
	sdRespirationPast12months Float,
	meanArterialPressurePast12months Float,
	medianArterialPressurePast12months Float,
	minArterialPressurePast12months Float,
	maxArterialPressurePast12months Float,
	lastArterialPressurePast12months Float,
	sdArterialPressurePast12months Float,
	meanOxygenSaturationPast12months Float,
	medianOxygenSaturationPast12months Float,
	minOxygenSaturationPast12months Float,
	maxOxygenSaturationPast12months Float,
	lastOxygenSaturationPast12months Float,
	sdOxygenSaturationPast12months Float,
	sdHeartRatePast12months Float,
	sdTemperaturePast12months Float,
	medianPaO2FiO2RatioPast12months Float,
	minPaO2FiO2RatioPast12months Float,
	maxPaO2FiO2RatioPast12months Float,
	lastPaO2FiO2RatioPast12months Float,
	sdPaO2FiO2RatioPast12months Float,
	cciWeight Float,
	magnitude Float,
	firstSystolicBPReadingInED Float,
	firstDiastolicBPReadingInED Float,
	firstRespirationReadingInED Float,
	firstArterialPressureReadingInED Float,
	firstOxygenSaturationReadingInED Float,
	isFirstSystolicBPInEDLess90OrGreater180 Bit,
	isFirstDiastolicBPInEDLess90OrGreater180 Bit,
	isFirstRespirationInEDLess8OrGreater24 Bit,
	isFirstArterialPressureInEDLess60OrGreater120 Bit,
	isFirstOxygenSaturationInEDLess88 Bit,
	issexMale Bit Not Null,
	issexFemale Bit Not Null,
	isadmitSourceEMD Bit Not Null,
	isadmitSourceMP Bit Not Null,
	isadmitSourceOther Bit Not Null,
	isadmitSourceHospTrans Bit Not Null,
	ismaritalStatusMarried Bit,
	ismaritalStatusNeverMarried Bit,
	ismaritalStatusWidowed Bit,
	ismaritalStatusDivorced Bit,
	isethnicityWhite Bit Not Null,
	isethnicityBlackOrAfricanAmerican Bit Not Null,
	isethnicityHispanicOrLatino Bit Not Null,
	isethnicityAsian Bit Not Null,
	proceduresCount Float Not Null
)